"use client";

import { useMemo } from "react";
import GoalCard from "../savings/GoalCard";
import { useFinanceStore } from "../shared/store";
import { SavingGoal } from "../shared/types";
import { useCurrency } from "../shared/useCurrency";

interface InvestingOverviewProps {
  onEditGoal: (goal: SavingGoal) => void;
  onAddLifeInsurance: () => void;
  isBudgetOpen: boolean;
  onToggleBudget: () => void;
}

const containsEmergency = (value: string) => value.toLowerCase().includes("emergency");

export default function InvestingOverview({
  onEditGoal,
  onAddLifeInsurance,
  isBudgetOpen,
  onToggleBudget,
}: InvestingOverviewProps) {
  const { formatCurrency } = useCurrency();
  const selectedMonth = useFinanceStore((state) => state.selectedMonth);
  const expenses = useFinanceStore((state) => state.expenses);
  const dashboardWindow = useFinanceStore((state) => state.dashboardWindow);
  const savingsCarryForwardEnabled = useFinanceStore((state) => state.savingsCarryForwardEnabled);
  const getWindowMonths = useFinanceStore((state) => state.getWindowMonths);
  const getSpentForMonth = useFinanceStore((state) => state.getSpentForMonth);
  const goals = useFinanceStore((state) => state.savingGoals);
  const investments = useFinanceStore((state) => state.investments);
  const lifeInsurances = useFinanceStore((state) => state.lifeInsurances);
  const deleteInvestment = useFinanceStore((state) => state.deleteInvestment);
  const deleteLifeInsurance = useFinanceStore((state) => state.deleteLifeInsurance);
  const toggleLifeInsurancePaid = useFinanceStore((state) => state.toggleLifeInsurancePaid);
  const adjustments = useFinanceStore((state) => state.adjustments);
  const savingsBudget = useFinanceStore((state) => state.savingsBudget);

  const scopedData = useMemo(() => {
    if (savingsCarryForwardEnabled) {
      return {
        goals,
        investments,
      };
    }

    const months = new Set(getWindowMonths(selectedMonth, dashboardWindow));

    return {
      goals: goals.filter((goal) => months.has(goal.date.slice(0, 7))),
      investments: investments.filter((item) => months.has(item.date.slice(0, 7))),
    };
  }, [dashboardWindow, getWindowMonths, goals, investments, savingsCarryForwardEnabled, selectedMonth]);

  const { totalSaved, totalInvested } = useMemo(() => {
    const saved = scopedData.goals.reduce((sum, goal) => sum + goal.savedAmount, 0);
    const invested = scopedData.investments.reduce((sum, item) => sum + item.amount, 0);
    return { totalSaved: saved, totalInvested: invested };
  }, [scopedData.goals, scopedData.investments]);
  const totalGoalTarget = useMemo(
    () => scopedData.goals.reduce((sum, goal) => sum + goal.targetAmount, 0),
    [scopedData.goals],
  );

  const combinedTotal = totalSaved + totalInvested;
  const savingsRemaining = savingsBudget - totalSaved;

  const emergencyMeta = useMemo(() => {
    const emergencyGoal =
      scopedData.goals.find((goal) => goal.isEmergencyFund) ??
      scopedData.goals.find((goal) => containsEmergency(goal.name) || containsEmergency(goal.category));

    const rollingThreeMonths = getWindowMonths(selectedMonth, 3);
    const averageExpense =
      rollingThreeMonths.reduce((sum, month) => sum + getSpentForMonth(month), 0) /
      Math.max(rollingThreeMonths.length, 1);

    const baseline = adjustments.essentialMonthlyExpense > 0 ? adjustments.essentialMonthlyExpense : averageExpense;
    const targetMonths = Math.max(adjustments.emergencyTargetMonths || 6, 1);
    const savedAmount = emergencyGoal?.savedAmount ?? 0;
    const monthsCovered = baseline > 0 ? savedAmount / baseline : 0;
    const progress = baseline > 0 ? Math.min((monthsCovered / targetMonths) * 100, 100) : 0;

    return {
      emergencyGoal,
      baseline,
      targetMonths,
      savedAmount,
      monthsCovered,
      progress,
    };
  }, [adjustments.emergencyTargetMonths, adjustments.essentialMonthlyExpense, getSpentForMonth, getWindowMonths, scopedData.goals, selectedMonth]);

  const sortedInsurances = [...lifeInsurances].sort((a, b) => b.dueDate.localeCompare(a.dueDate));
  const paidInsuranceIdsForMonth = useMemo(
    () =>
      new Set(
        expenses
          .filter(
            (expense) =>
              expense.sourceType === "insurance_premium" &&
              expense.sourceMonth === selectedMonth &&
              expense.isAutoGenerated,
          )
          .map((expense) => expense.sourceId)
          .filter((id): id is string => Boolean(id)),
      ),
    [expenses, selectedMonth],
  );

  return (
    <section className="px-4 pt-3 pb-4 space-y-4">
      <div className="glass-card rounded-2xl p-4">
        <div className="flex items-end justify-between gap-2 mb-2">
          <div>
            <p className="text-[11px] uppercase tracking-[0.14em] text-white/55 font-semibold">Investing Snapshot</p>
            <p className="text-2xl font-bold text-white">{formatCurrency(combinedTotal)}</p>
          </div>
          <div className="flex flex-col items-end gap-1">
            <span className="text-xs text-[#9cf4e4] font-semibold">Total Managed</span>
            <button
              type="button"
              onClick={onToggleBudget}
              className={`h-6 px-2 rounded-full border text-[10px] font-semibold ${
                isBudgetOpen
                  ? "border-[#00C9A7]/60 bg-[#00C9A7]/18 text-[#bdfdee]"
                  : "border-white/20 bg-white/[0.08] text-white/70"
              }`}
            >
              Budget
            </button>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-2 text-xs">
          <div className="rounded-xl border border-white/15 bg-white/5 p-2.5">
            <p className="text-white/55 uppercase tracking-wide">Goal Savings</p>
            <p className="text-sm font-semibold text-white mt-0.5">{formatCurrency(totalSaved)}</p>
          </div>
          <div className="rounded-xl border border-white/15 bg-white/5 p-2.5">
            <p className="text-white/55 uppercase tracking-wide">Investments</p>
            <p className="text-sm font-semibold text-white mt-0.5">{formatCurrency(totalInvested)}</p>
          </div>
        </div>

        <p className="mt-2 text-[11px] text-white/60">
          Savings budget: {formatCurrency(savingsBudget)} - Remaining: {formatCurrency(Math.abs(savingsRemaining))} {savingsRemaining < 0 ? "over" : "left"}
        </p>
        <p className="mt-1 text-[11px] text-white/60">
          {savingsCarryForwardEnabled ? "Carry forward ON: all-time totals" : `Carry forward OFF: last ${dashboardWindow} month(s)`}
        </p>
      </div>

      <div className="glass-card rounded-2xl p-4">
        <div className="flex items-center justify-between mb-2">
          <h3 className="text-sm font-semibold text-white">Emergency Fund Tracker</h3>
          <span className="text-xs text-[#6b7280]">Target: {emergencyMeta.targetMonths} months</span>
        </div>

        {emergencyMeta.emergencyGoal ? (
          <>
            <p className="text-xs text-[#6b7280] mb-1">
              {emergencyMeta.emergencyGoal.name} - {formatCurrency(emergencyMeta.savedAmount)} saved
            </p>
            <p className="text-sm font-semibold text-[#f0f0ff] mb-2">
              {emergencyMeta.monthsCovered.toFixed(1)} months covered
            </p>
            <div className="h-2 rounded-full bg-white/10 overflow-hidden">
              <div
                className="h-full rounded-full bg-[#00C9A7] drop-shadow-[0_0_4px_currentColor]"
                style={{ width: `${emergencyMeta.progress}%` }}
              />
            </div>
            <p className="text-[11px] text-[#6b7280] mt-2">
              Baseline expense: {formatCurrency(emergencyMeta.baseline || 0)} / month
            </p>
            <p className="text-[11px] text-[#6b7280] mt-1">
              {emergencyMeta.monthsCovered >= emergencyMeta.targetMonths ? "On track" : "Below target"}
            </p>
          </>
        ) : (
          <p className="text-sm text-[#6b7280]">Create a goal and mark it as Emergency Fund to track coverage.</p>
        )}
      </div>

      <div className="space-y-3">
        <div className="flex items-center justify-between px-1">
          <h3 className="text-sm font-semibold text-white">Life Insurance</h3>
          <button
            type="button"
            onClick={onAddLifeInsurance}
            className="h-7 px-2.5 rounded-lg border border-white/20 bg-white/[0.08] text-[11px] font-semibold text-[#c7dfdb]"
          >
            Add
          </button>
        </div>

        {sortedInsurances.length === 0 ? (
          <div className="glass-card rounded-2xl p-6 text-center">
            <p className="text-sm text-white/80">No life insurance entries yet.</p>
            <p className="text-xs text-white/60 mt-1">Add your monthly premium and EMI date.</p>
          </div>
        ) : (
          <div className="space-y-2.5">
            {sortedInsurances.map((item) => {
              const isPaidForMonth = paidInsuranceIdsForMonth.has(item.id);
              return (
                <article key={item.id} className="glass-card rounded-2xl p-3.5">
                <div className="flex items-start justify-between gap-2">
                  <div>
                    <h4 className="text-sm font-semibold text-white">{item.providerName}</h4>
                    <p className="text-xs text-white/65">{item.planName}</p>
                    <p className="text-[11px] text-white/45 mt-1">Due: {item.dueDate}</p>
                  </div>
                  <div className="flex flex-col items-end gap-1">
                    <p className="text-sm font-bold text-[#9cf4e4]">{formatCurrency(item.monthlyAmount)}</p>
                    <div className="flex items-center gap-1">
                      <button
                        type="button"
                        onClick={() => toggleLifeInsurancePaid(item.id)}
                        className={`h-7 px-2.5 rounded-lg text-[11px] font-semibold ${
                          isPaidForMonth
                            ? "bg-[rgba(0,201,167,0.2)] text-[#00C9A7]"
                            : "bg-[rgba(255,140,66,0.2)] text-[#FF8C42]"
                        }`}
                      >
                        {isPaidForMonth ? "Paid This Month" : "Unpaid This Month"}
                      </button>
                      <button
                        type="button"
                        onClick={() => deleteLifeInsurance(item.id)}
                        className="size-7 rounded-lg border border-[rgba(255,140,66,0.35)] bg-[rgba(255,140,66,0.12)] text-[#FF8C42] inline-flex items-center justify-center"
                        title="Delete insurance"
                      >
                        <span className="material-symbols-outlined text-[14px]">delete</span>
                      </button>
                    </div>
                  </div>
                </div>
                {item.note && <p className="text-xs text-white/65 mt-2 whitespace-normal break-words">{item.note}</p>}
                </article>
              );
            })}
          </div>
        )}
      </div>

      <div className="space-y-3">
        <div className="flex items-center justify-between px-1">
          <h3 className="text-sm font-semibold text-white">Goals</h3>
          <span className="text-xs text-white/55">{scopedData.goals.length} total</span>
        </div>
        <div className="glass-card rounded-xl p-2.5 flex items-center justify-between">
          <p className="text-[10px] uppercase tracking-wide text-white/55">Saved / Target</p>
          <p className="text-xs font-semibold text-[#f0f0ff]">
            {formatCurrency(totalSaved)} / {formatCurrency(totalGoalTarget)}
          </p>
        </div>

        {scopedData.goals.length === 0 ? (
          <div className="glass-card rounded-2xl p-6 text-center">
            <p className="text-sm text-white/80">No goals yet.</p>
            <p className="text-xs text-white/60 mt-1">Use the add button to create your first savings goal.</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 min-[420px]:grid-cols-2 gap-2.5">
            {scopedData.goals.map((goal) => (
              <GoalCard key={goal.id} goal={goal} onEditGoal={onEditGoal} />
            ))}
          </div>
        )}
      </div>

      <div className="space-y-3">
        <div className="flex items-center justify-between px-1">
          <h3 className="text-sm font-semibold text-white">Investments</h3>
          <span className="text-xs text-white/55">{scopedData.investments.length}</span>
        </div>

        {scopedData.investments.length === 0 ? (
          <div className="glass-card rounded-2xl p-6 text-center">
            <p className="text-sm text-white/80">No investments yet.</p>
            <p className="text-xs text-white/60 mt-1">Use the add button to add your first investment.</p>
          </div>
        ) : (
          <div className="space-y-2.5">
            {scopedData.investments.map((item) => (
              <article key={item.id} className="glass-card rounded-2xl p-3.5">
                <div className="flex items-start justify-between gap-2">
                  <div>
                    <h4 className="text-sm font-semibold text-white">{item.title}</h4>
                    <p className="text-xs text-white/65">{item.category}</p>
                    <p className="text-[11px] text-white/45 mt-1">{item.date}</p>
                  </div>
                  <div className="flex flex-col items-end gap-1">
                    <p className="text-sm font-bold text-[#9cf4e4]">{formatCurrency(item.amount)}</p>
                    <button
                      type="button"
                      onClick={() => deleteInvestment(item.id)}
                      className="size-7 rounded-lg border border-[rgba(255,140,66,0.35)] bg-[rgba(255,140,66,0.12)] text-[#FF8C42] inline-flex items-center justify-center"
                      title="Delete investment"
                    >
                      <span className="material-symbols-outlined text-[14px]">delete</span>
                    </button>
                  </div>
                </div>
                {item.note && <p className="text-xs text-white/65 mt-2 truncate">{item.note}</p>}
              </article>
            ))}
          </div>
        )}
      </div>
    </section>
  );
}
