"use client";

import jsPDF from "jspdf";
import { useFinanceStore } from "./shared/store";

const PAGE = {
  width: 210,
  height: 297,
  margin: 15,
  contentWidth: 180,
  footerReserve: 10,
};

const COLORS = {
  white: "#FFFFFF",
  appGreen: "#2D6A4F",
  reportSub: "#555555",
  reportMeta: "#888888",
  divider: "#E0E0E0",
  sectionTitle: "#333333",
  rowAlt: "#F9F9F9",
  rowBase: "#FFFFFF",
  text: "#333333",
  txHeader: "#37474F",
  txRowAlt: "#F5F5F5",
  txText: "#444444",
  spendSummaryHeader: "#4CAF50",
  lendSummaryHeader: "#FF9800",
  categoryHeader: "#1976D2",
  categoryAlt: "#EEF2FF",
  lendingHeader: "#546E7A",
  pendingBg: "#FFF3E0",
  pendingText: "#E65100",
  paidBg: "#E8F5E9",
  paidText: "#2E7D32",
  footerText: "#AAAAAA",
};

type Align = "left" | "right" | "center";

type TableColumn = {
  key: string;
  label: string;
  width: number;
  align?: Align;
  clip?: boolean;
};

type TableRow = Record<string, string>;

type TableOptions = {
  sectionTitle: string;
  columns: TableColumn[];
  rows: TableRow[];
  headerBg: string;
  rowBg: string;
  rowAltBg: string;
  textColor: string;
  headerFontSize?: number;
  bodyFontSize?: number;
  statusBadge?: boolean;
};

const MM_PER_PT = 0.352778;
const CELL_PAD_X = 2.5;
const CELL_PAD_Y = 2;

const toRgb = (hex: string): [number, number, number] => {
  const normalized = hex.replace("#", "");
  const value = normalized.length === 3
    ? normalized.split("").map((char) => char + char).join("")
    : normalized;
  const num = Number.parseInt(value, 16);
  return [(num >> 16) & 255, (num >> 8) & 255, num & 255];
};

const setColor = (doc: jsPDF, mode: "text" | "draw" | "fill", hex: string) => {
  const [r, g, b] = toRgb(hex);
  if (mode === "text") doc.setTextColor(r, g, b);
  if (mode === "draw") doc.setDrawColor(r, g, b);
  if (mode === "fill") doc.setFillColor(r, g, b);
};

const safeText = (value?: string) => {
  const text = (value ?? "").replace(/[']/g, "\u20B9").trim();
  return text.length > 0 ? text : "-";
};

const formatMonth = (month: string) => {
  const [year, monthNo] = month.split("-").map(Number);
  if (!year || !monthNo) return month;
  return new Date(year, monthNo - 1, 1).toLocaleDateString("en-US", {
    month: "long",
    year: "numeric",
  });
};

const formatDate = (raw?: string) => {
  if (!raw) return "-";
  const date = new Date(`${raw}T00:00:00`);
  if (Number.isNaN(date.getTime())) return raw;
  return date.toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
};

const lineHeightMm = (fontSize: number) => fontSize * MM_PER_PT * 1.2;

const ellipsize = (doc: jsPDF, text: string, maxWidth: number) => {
  if (doc.getTextWidth(text) <= maxWidth) return text;
  const suffix = "...";
  let out = text;
  while (out.length > 0 && doc.getTextWidth(out + suffix) > maxWidth) {
    out = out.slice(0, -1);
  }
  return out.length > 0 ? out + suffix : suffix;
};

const getTextLines = (doc: jsPDF, text: string, maxWidth: number, clip: boolean) => {
  if (clip) {
    return [ellipsize(doc, text, maxWidth)];
  }
  const lines = doc.splitTextToSize(text, maxWidth) as string[];
  return lines.length > 0 ? lines : ["-"];
};

const resolveRupeeSymbol = (doc: jsPDF) => {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const rupee = "\u20B9";
  const rupeeWidth = doc.getTextWidth(rupee);
  const questionWidth = doc.getTextWidth("?");
  return Math.abs(rupeeWidth - questionWidth) > 0.01 ? rupee : "Rs.";
};

const formatMoneyFactory = (currencyPrefix: string) => {
  const numberFormat = new Intl.NumberFormat("en-IN", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
  return (value: number) => `${currencyPrefix}${numberFormat.format(Number.isFinite(value) ? value : 0)}`;
};

const drawPageFooter = (doc: jsPDF) => {
  const totalPages = doc.getNumberOfPages();
  const yBorder = PAGE.height - PAGE.margin - PAGE.footerReserve + 1;
  const yText = PAGE.height - 6;

  for (let page = 1; page <= totalPages; page += 1) {
    doc.setPage(page);
    doc.setLineWidth(0.1);
    setColor(doc, "draw", COLORS.divider);
    doc.line(PAGE.margin, yBorder, PAGE.width - PAGE.margin, yBorder);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    setColor(doc, "text", COLORS.footerText);
    doc.text(`Page ${page} of ${totalPages}`, PAGE.width / 2, yText, { align: "center", maxWidth: 50 });
    doc.text("Generated by Poisa", PAGE.width - PAGE.margin, yText, { align: "right", maxWidth: 50 });
  }
};

const drawReportHeader = (doc: jsPDF, reportType: string, monthLabel: string, currencyLabel: string) => {
  let y = PAGE.margin;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  setColor(doc, "text", COLORS.appGreen);
  doc.text("Poisa", PAGE.margin, y, { baseline: "top", maxWidth: 80 });

  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(13);
  setColor(doc, "text", COLORS.reportSub);
  doc.text(reportType, PAGE.margin, y, { baseline: "top", maxWidth: 100 });

  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  setColor(doc, "text", COLORS.reportMeta);
  doc.text(`Month: ${monthLabel}   Currency: ${currencyLabel}`, PAGE.margin, y, { baseline: "top", maxWidth: PAGE.contentWidth });

  y += 6;
  doc.setLineWidth(0.1);
  setColor(doc, "draw", COLORS.divider);
  doc.line(PAGE.margin, y, PAGE.width - PAGE.margin, y);

  return y + 4;
};

const drawSectionTitle = (doc: jsPDF, y: number, text: string) => {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  setColor(doc, "text", COLORS.sectionTitle);
  doc.text(text, PAGE.margin, y, { baseline: "top", maxWidth: PAGE.contentWidth });
  return y + 6;
};

const drawTable = (doc: jsPDF, startY: number, options: TableOptions) => {
  const headerFontSize = options.headerFontSize ?? 10;
  const bodyFontSize = options.bodyFontSize ?? 10;
  const pageBottom = PAGE.height - PAGE.margin - PAGE.footerReserve;
  const borderColor = COLORS.divider;

  let y = drawSectionTitle(doc, startY, options.sectionTitle);

  const drawHeaderRow = () => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(headerFontSize);
    setColor(doc, "fill", options.headerBg);
    setColor(doc, "draw", borderColor);

    const headerHeight = lineHeightMm(headerFontSize) + CELL_PAD_Y * 2;
    let x = PAGE.margin;

    options.columns.forEach((column) => {
      doc.rect(x, y, column.width, headerHeight, "FD");
      setColor(doc, "text", COLORS.white);
      const align = column.align ?? "left";
      const textX = align === "right" ? x + column.width - CELL_PAD_X : align === "center" ? x + column.width / 2 : x + CELL_PAD_X;
      doc.text(column.label, textX, y + CELL_PAD_Y, {
        align,
        baseline: "top",
        maxWidth: column.width - CELL_PAD_X * 2,
      });
      x += column.width;
    });

    y += headerHeight;
  };

  if (y + lineHeightMm(headerFontSize) + CELL_PAD_Y * 2 > pageBottom) {
    doc.addPage();
    y = PAGE.margin;
  }

  drawHeaderRow();

  if (options.rows.length === 0) {
    options.rows = [{ [options.columns[0].key]: "No data", [options.columns[options.columns.length - 1].key]: "-" }];
  }

  options.rows.forEach((row, rowIndex) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(bodyFontSize);

    const lineH = lineHeightMm(bodyFontSize);
    const lineCounts = options.columns.map((column) => {
      const value = safeText(row[column.key]);
      const lines = getTextLines(doc, value, column.width - CELL_PAD_X * 2, Boolean(column.clip));
      return lines.length;
    });

    const rowHeight = Math.max(lineH + CELL_PAD_Y * 2, Math.max(...lineCounts) * lineH + CELL_PAD_Y * 2);

    if (y + rowHeight > pageBottom) {
      doc.addPage();
      y = PAGE.margin;
      drawHeaderRow();
    }

    const rowFill = rowIndex % 2 === 0 ? options.rowBg : options.rowAltBg;
    let x = PAGE.margin;

    options.columns.forEach((column) => {
      setColor(doc, "fill", rowFill);
      setColor(doc, "draw", borderColor);
      doc.rect(x, y, column.width, rowHeight, "FD");

      const rawValue = safeText(row[column.key]);
      const align = column.align ?? "left";
      const innerWidth = column.width - CELL_PAD_X * 2;
      const lines = getTextLines(doc, rawValue, innerWidth, Boolean(column.clip));

      if (options.statusBadge && column.key === "status") {
        const normalized = rawValue.toLowerCase() === "pending" ? "Pending" : "Paid";
        const badgeBg = normalized === "Pending" ? COLORS.pendingBg : COLORS.paidBg;
        const badgeText = normalized === "Pending" ? COLORS.pendingText : COLORS.paidText;

        doc.setFont("helvetica", "bold");
        doc.setFontSize(8.5);

        const textWidth = Math.min(doc.getTextWidth(normalized), innerWidth - 4);
        const badgeWidth = Math.min(textWidth + 5, innerWidth);
        const badgeHeight = lineHeightMm(8.5) + 1.8;
        const badgeX = x + (column.width - badgeWidth) / 2;
        const badgeY = y + (rowHeight - badgeHeight) / 2;

        setColor(doc, "fill", badgeBg);
        setColor(doc, "draw", badgeBg);
        doc.roundedRect(badgeX, badgeY, badgeWidth, badgeHeight, 1, 1, "FD");

        setColor(doc, "text", badgeText);
        doc.text(normalized, badgeX + badgeWidth / 2, badgeY + 1.2, {
          align: "center",
          baseline: "top",
          maxWidth: badgeWidth - 2,
        });

        doc.setFont("helvetica", "normal");
        doc.setFontSize(bodyFontSize);
      } else {
        setColor(doc, "text", options.textColor);
        const textX = align === "right" ? x + column.width - CELL_PAD_X : align === "center" ? x + column.width / 2 : x + CELL_PAD_X;

        doc.text(lines, textX, y + CELL_PAD_Y, {
          align,
          baseline: "top",
          maxWidth: innerWidth,
        });
      }

      x += column.width;
    });

    y += rowHeight;
  });

  return y + 5;
};

export default function DownloadSpendingPdfButton() {
  const selectedMonth = useFinanceStore((state) => state.selectedMonth);
  const currency = useFinanceStore((state) => state.currency);
  const expenses = useFinanceStore((state) => state.expenses);
  const loans = useFinanceStore((state) => state.loans);
  const moneyTookEntries = useFinanceStore((state) => state.moneyTookEntries);
  const personalLoans = useFinanceStore((state) => state.personalLoans);

  const onDownload = () => {
    const monthExpenses = expenses
      .filter((expense) => expense.date.slice(0, 7) === selectedMonth)
      .sort((a, b) => b.date.localeCompare(a.date));

    const totalSpent = monthExpenses.reduce((sum, expense) => sum + expense.amount, 0);
    const avgSpent = monthExpenses.length > 0 ? totalSpent / monthExpenses.length : 0;

    const categoryTotals = monthExpenses.reduce<Record<string, number>>((acc, expense) => {
      const key = safeText(expense.category);
      acc[key] = (acc[key] || 0) + expense.amount;
      return acc;
    }, {});

    const sortedCategories = Object.entries(categoryTotals).sort((a, b) => b[1] - a[1]);
    const highestCategory = sortedCategories[0]?.[1] ?? 0;

    const lentRowsData = [...loans]
      .sort((a, b) => b.date.localeCompare(a.date))
      .map((loan) => {
        const repaid = loan.repaidAmount;
        const outstanding = Math.max(loan.amount - repaid, 0);
        return {
          date: formatDate(loan.date),
          person: safeText(loan.personName),
          lent: loan.amount,
          repaid,
          outstanding,
          status: outstanding > 0 ? "Pending" : "Paid",
        };
      });

    const borrowedFromEntries = moneyTookEntries.map((entry) => {
      const repaid = entry.payments.reduce((sum, payment) => sum + payment.amount, 0);
      const outstanding = Math.max(entry.amount - repaid, 0);
      return {
        lender: safeText(entry.lenderName),
        borrowed: entry.amount,
        repaid,
        outstanding,
        due: formatDate(entry.dueDate),
        status: outstanding > 0 ? "Pending" : "Paid",
      };
    });

    const borrowedFromPersonalLoans = personalLoans.map((loan) => {
      const repaid = loan.payments.reduce((sum, payment) => sum + payment.amount, 0);
      const outstanding = loan.outstandingAmount ?? Math.max((loan.totalLoanAmount ?? 0) - repaid, 0);
      const borrowed = loan.totalLoanAmount ?? repaid + outstanding;
      return {
        lender: safeText(loan.lenderName),
        borrowed,
        repaid,
        outstanding,
        due: formatDate(loan.nextEmiDate),
        status: outstanding > 0 ? "Pending" : "Paid",
      };
    });

    const borrowedRowsData = [...borrowedFromEntries, ...borrowedFromPersonalLoans].sort((a, b) => b.due.localeCompare(a.due));

    const totalLentOutstanding = lentRowsData.reduce((sum, row) => sum + row.outstanding, 0);
    const totalBorrowedOutstanding = borrowedRowsData.reduce((sum, row) => sum + row.outstanding, 0);
    const totalLent = lentRowsData.reduce((sum, row) => sum + row.lent, 0);

    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

    setColor(doc, "fill", COLORS.white);
    doc.rect(0, 0, PAGE.width, PAGE.height, "F");

    const rupee = resolveRupeeSymbol(doc);
    const formatMoney = formatMoneyFactory(rupee);

    const spendingSummaryRows: TableRow[] = [
      { metric: "Total Transactions", value: String(monthExpenses.length) },
      { metric: "Total Spent", value: formatMoney(totalSpent) },
      { metric: "Average Transaction", value: formatMoney(avgSpent) },
      { metric: "Highest Category Spend", value: formatMoney(highestCategory) },
    ];

    const categoryRows: TableRow[] = sortedCategories.map(([category, amount]) => ({
      category,
      amount: formatMoney(amount),
      share: `${totalSpent > 0 ? ((amount / totalSpent) * 100).toFixed(2) : "0.00"}%`,
    }));

    const spendingTransactionRows: TableRow[] = monthExpenses.map((expense) => ({
      date: formatDate(expense.date),
      name: safeText(expense.name),
      category: safeText(expense.category),
      amount: formatMoney(expense.amount),
      note: safeText(expense.note),
    }));

    let y = drawReportHeader(doc, "Spending Report", formatMonth(selectedMonth), currency);

    y = drawTable(doc, y, {
      sectionTitle: "Summary",
      columns: [
        { key: "metric", label: "Metric", width: 120, align: "left" },
        { key: "value", label: "Value", width: 60, align: "right" },
      ],
      rows: spendingSummaryRows,
      headerBg: COLORS.spendSummaryHeader,
      rowBg: COLORS.rowBase,
      rowAltBg: COLORS.rowAlt,
      textColor: COLORS.text,
      headerFontSize: 10,
      bodyFontSize: 10,
    });

    y = drawTable(doc, y, {
      sectionTitle: "Category Breakdown",
      columns: [
        { key: "category", label: "Category", width: 90, align: "left" },
        { key: "amount", label: "Amount", width: 55, align: "right" },
        { key: "share", label: "Share %", width: 35, align: "right" },
      ],
      rows: categoryRows,
      headerBg: COLORS.categoryHeader,
      rowBg: COLORS.rowBase,
      rowAltBg: COLORS.categoryAlt,
      textColor: COLORS.text,
      headerFontSize: 10,
      bodyFontSize: 10,
    });

    y = drawTable(doc, y, {
      sectionTitle: "Transactions",
      columns: [
        { key: "date", label: "Date", width: 28, align: "left", clip: true },
        { key: "name", label: "Name", width: 40, align: "left", clip: true },
        { key: "category", label: "Category", width: 35, align: "left", clip: true },
        { key: "amount", label: "Amount", width: 32, align: "right", clip: true },
        { key: "note", label: "Note", width: 45, align: "left", clip: true },
      ],
      rows: spendingTransactionRows,
      headerBg: COLORS.txHeader,
      rowBg: COLORS.rowBase,
      rowAltBg: COLORS.txRowAlt,
      textColor: COLORS.txText,
      headerFontSize: 9,
      bodyFontSize: 9,
    });

    doc.addPage();
    setColor(doc, "fill", COLORS.white);
    doc.rect(0, 0, PAGE.width, PAGE.height, "F");

    const lendingSummaryRows: TableRow[] = [
      { metric: "Total Lent", value: formatMoney(totalLent) },
      { metric: "Money I Lent Outstanding", value: formatMoney(totalLentOutstanding) },
      { metric: "Money I Borrowed Outstanding", value: formatMoney(totalBorrowedOutstanding) },
    ];

    const lendingLentRows: TableRow[] = lentRowsData.map((row) => ({
      date: row.date,
      person: row.person,
      lent: formatMoney(row.lent),
      repaid: formatMoney(row.repaid),
      outstanding: formatMoney(row.outstanding),
      status: row.status,
    }));

    const lendingBorrowedRows: TableRow[] = borrowedRowsData.map((row) => ({
      lender: row.lender,
      borrowed: formatMoney(row.borrowed),
      repaid: formatMoney(row.repaid),
      outstanding: formatMoney(row.outstanding),
      due: row.due,
      status: row.status,
    }));

    y = drawReportHeader(doc, "Lending Report", formatMonth(selectedMonth), currency);

    y = drawTable(doc, y, {
      sectionTitle: "Summary",
      columns: [
        { key: "metric", label: "Metric", width: 120, align: "left" },
        { key: "value", label: "Value", width: 60, align: "right" },
      ],
      rows: lendingSummaryRows,
      headerBg: COLORS.lendSummaryHeader,
      rowBg: COLORS.rowBase,
      rowAltBg: COLORS.rowAlt,
      textColor: COLORS.text,
      headerFontSize: 10,
      bodyFontSize: 10,
    });

    y = drawTable(doc, y, {
      sectionTitle: "Money I Lent",
      columns: [
        { key: "date", label: "Date", width: 28, align: "left", clip: true },
        { key: "person", label: "Person", width: 40, align: "left" },
        { key: "lent", label: "Lent", width: 28, align: "right" },
        { key: "repaid", label: "Repaid", width: 28, align: "right" },
        { key: "outstanding", label: "Outstanding", width: 32, align: "right" },
        { key: "status", label: "Status", width: 24, align: "center" },
      ],
      rows: lendingLentRows,
      headerBg: COLORS.lendingHeader,
      rowBg: COLORS.rowBase,
      rowAltBg: COLORS.rowAlt,
      textColor: COLORS.txText,
      headerFontSize: 9,
      bodyFontSize: 9,
      statusBadge: true,
    });

    drawTable(doc, y, {
      sectionTitle: "Money I Borrowed",
      columns: [
        { key: "lender", label: "Lender", width: 40, align: "left" },
        { key: "borrowed", label: "Borrowed", width: 28, align: "right" },
        { key: "repaid", label: "Repaid", width: 28, align: "right" },
        { key: "outstanding", label: "Outstanding", width: 28, align: "right" },
        { key: "due", label: "Due", width: 28, align: "left", clip: true },
        { key: "status", label: "Status", width: 28, align: "center" },
      ],
      rows: lendingBorrowedRows,
      headerBg: COLORS.lendingHeader,
      rowBg: COLORS.rowBase,
      rowAltBg: COLORS.rowAlt,
      textColor: COLORS.txText,
      headerFontSize: 9,
      bodyFontSize: 9,
      statusBadge: true,
    });

    drawPageFooter(doc);

    doc.save(`poisa-spending-lending-report-${selectedMonth}.pdf`);
  };

  return (
    <button
      type="button"
      onClick={onDownload}
      className="inline-flex items-center gap-2 px-3 h-9 rounded-xl border border-[rgba(255,255,255,0.08)] bg-[#1a1a26] text-xs font-semibold text-[#f0f0ff] hover:border-[#00C896]/70 transition-colors"
    >
      <span className="material-symbols-outlined text-base">picture_as_pdf</span>
      Download Spending PDF
    </button>
  );
}
